### ISSUE TITLE
C-c C-c ledger-toggle-current searches backwards indefinitely

### ISSUE THREAD

**Issue by jstamant** [ledger/ledger-mode#374] opened 2023-09-25 21:42 UTC
If the cursor isn't on a transaction, hitting `C-c C-c` (`ledger-toggle-current`) will search backwards until it finds a transaction, and then toggles its state.

The behavior is the same as in issue #316, where I explain this problem in a bit more detail. Like in #316, my suggestion here is to add some validation that only lets a user perform `ledger-toggle-current` when point is on a valid transaction or posting.

I'll probably provide a fix in a PR shortly.

**Comment by bcc32** [comment] 2024-03-23 21:13
I can't reproduce this behavior.  There have been a couple recent changes to `ledger-toggle-current`'s implementation, so it might be fixed by now?

Can you provide a sample ledger file and a step-by-step reproduction example?

**Comment by jstamant** [comment] 2024-03-24 13:35
Hey, Aaron. Gladly:

Upgrading ledger-mode to today's version on MELPA (20240322.2155) still produces the behavior for me.

### Steps to reproduce

1. Download [this sample file](https://github.com/ledger/ledger-mode/files/14735571/sample.txt) and open it with `ledger-mode` as the major mode
2. Goto to line 6 and hit `C-c C-c` (`ledger-toggle-current`)
3. Notice that the transaction above gets toggle. If this were a long section of comments, the command would silently occur.
4. Add a full window's worth of newlines at line 4 so that the transaction is no longer on screen
5. Goto the end of the file `M-x end-of-buffer`, and run `M-x ledger-toggle-current` again
6. Notice that the status for the transaction on line 1 get toggled. Silently

**Comment by bcc32** [comment] 2024-03-24 16:19
Ah, thanks for the example.  It turns out I also had to set `ledger-clear-whole-transactions` non-nil to trigger the bug.  Fixing

**Closed** 2024-03-24 23:30 UTC
