### ISSUE TITLE
ledger-mode-clean-buffer truncates account declarations

### ISSUE THREAD

**Issue by alraban** [ledger/ledger-mode#79] opened 2018-01-29 02:08 UTC
When I run ledger-mode-clean-buffer all of my account declarations become truncated in an identical fashion which immediately breaks the ledger file.  Specifically:

`account Expenses`

becomes:

`acExpenses`

This happens to all my account declarations.  Once that happens, running reports immediately errors and I can no longer use the file with the command line ledger until I manually fix all the account declarations.  ledger-mode-clean-buffer worked perfectly until a recent update to ledger-mode.  Other types of declarations (such as for commodities) appear unaffected.  

Ledger version is 3.1.1-20160111; ledger-mode is the version currently in MELPA (20180126.1808).  Please let me know if I can provide any other useful information.

**Comment by cpitclaudel** [comment] 2018-01-29 03:32
Thanks, I can reproduce this. Looking into it :)

**Comment by cpitclaudel** [comment] 2018-01-29 04:13
I pushed a fix to branch 72-cropped-account-lines (https://github.com/ledger/ledger-mode/tree/79-cropped-account-lines).   Do you think you could confirm the fix by checking that branch out?

Background: this is due to recent completion changes that added account directives to the "account name" regexp (making them available for completion).  This changed caused the reformatter to want to align account names on account directive lines to the 2nd column — hence the cropping to 2 characters (cc @purcell)

We should have a test for this, but even better we should have a test for the cleanup feature (I don't think we have one at all at the moment).  I think ledger has a feature to anonymize a ledger file.  @alraban, would you like to help create such a test?

**Comment by purcell** [comment] 2018-01-29 08:27
Yep, sorry - my bad, @alraban. Your fix looks good, @cpitclaudel. Feel free to merge if it works for you locally.

**Comment by cpitclaudel** [comment] 2018-01-29 09:58
Thanks @purcell :) I'll wait for confirmation from @alraban .

**Comment by alraban** [comment] 2018-01-29 23:00
I just tested the revised version and that appears to fix the issue entirely.   Thanks so much for the fix and prompt attention!  

With respect to helping create a test, I am not a professional developer and I've never written a test for software before (or interacted with a build system), so I don't know what is involved. Regrettably, I also know just enough elisp to be a nuisance.  I could certainly furnish a file that illustrated the clean-up problem if that's what you mean, or with some guidance about what's involved/expected I could certainly try and write a test.

Regardless, thanks very much for all your work on this package!

**Closed** 2018-01-29 23:19 UTC

**Comment by cpitclaudel** [comment] 2018-01-29 23:29
> I just tested the revised version and that appears to fix the issue entirely.   Thanks so much for the fix and prompt attention!

Thanks so much for the report and the help with testing the fix!

> With respect to helping create a test, I am not a professional developer and I've never written a test for software before (or interacted with a build system), so I don't know what is involved. 

I think we've all been there :) If you're excited about teaching yourself, creating tests are one of the easiest ways to get started.  And people are usually happy to do a bit of mentoring.

> I could furnish a file that illustrated the clean-up problem if that's what you mean,

That would be super.  Currently, most of the cleanup feature in ledger-mode is untested, which is a shame (you wouldn't want to lose transactions).

> or with some guidance about what's involved/expected I could certainly try and write a test.

If that sounds fun to you, I'm happy to give some guidance.  What I have in mind is called an integration test (as opposed to a unit test): it checks a feature in an "end-to-end" way.  What I'd do is take a simple ledger file with some accounts and transactions, and make various modifications that you'd expect a clean-up to revert.  I'd save the file as dirty.ledger, then run a cleanup on it and save that as clean.ledger.  The last step would be to write an ELisp snippet that loads the dirty file, clean it up, and makes sure that the buffer contains exactly the same thing as the dirty file.

Something like this:

```
(let ((clean (with-temp-buffer
               (insert-file-contents "clean.ledger")
               (buffer-string))))
  (with-temp-buffer
    (insert-file-contents "dirty.ledger")
    (ledger-mode-clean-buffer)
    (should
     (equal (buffer-string)
            clean))))
```

(`should` is a special form; see the file test/post-test.el).

As a simple start, you could do everything with strings directly in the buffer, like the other tests in that file.

Hope this helps :) It will certainly help us to get more tests.
(No pressure to work on this, of course; it's just if it's fun for you.)
