### ISSUE TITLE
ledger-acounts-file not nil cause an empty completion canditates list

### ISSUE THREAD

**Issue by albreche** [ledger/ledger-mode#402] opened 2024-03-10 22:36 UTC
Hi there,   
 latest ledger-mode (setup with straight) and emacs-29.2 . 

When ledger-accounts-file variable is set with an account files, ledger-complete-at-point returns an empty list.  Under the hood as i understood, the bug come from ledger--account-list which does note return the list built from reading ledger-account-files and appending it to ledger-accounts-list-in-buffer.  It lacks a call to buffer-string : 
```lisp
(defun ledger-accounts-list ()
  "Return a list of all known account names as strings.
Looks in `ledger-accounts-file' if set, otherwise the current buffer."
  (if ledger-accounts-file
      (let ((f ledger-accounts-file))
        (with-temp-buffer
          (insert-file-contents f)
          (ledger-accounts-list-in-buffer)
          (split-string (buffer-string) "\n") // absent in master
          ))
    (ledger-accounts-list-in-buffer)))
```

btw, there's no verification on the content on the file in  this method.

**Comment by bcc32** [comment] 2024-03-10 23:34
I think you need to use `account NAME` declarations in the accounts file, not just a list of account names.  See the docstring of `ledger-accounts-file`:

```
The path to an optional file in which all accounts are used or declared.
This file will then be used as a source for account name completions.
```

"declared" means the `account` directive as documented [here](https://ledger-cli.org/doc/ledger3.html#index-account).

**Comment by purcell** [comment] 2024-03-11 16:49
Yep, I just updated the docstring to mention the docstring, thanks @bcc32.

**Comment by bcc32** [comment] 2024-03-16 22:11
I think the feature is working as intended and no further change is required, so I'm closing the issue.

**Closed** 2024-03-17 19:01 UTC
