### ISSUE TITLE
ledger-reconcile no longer plays nicely with helm

### ISSUE THREAD

**Issue by johnrakestraw** [ledger/ledger-mode#110] opened 2018-04-15 00:33 UTC
I've used helm with ledger for at least a year. Recent updates have introduced a problem. 

Assume that both helm-mode and ledger-mode are active and the attached very simple ledger file.

I execute ledger-reconcile. In response to request "Account to reconcile:" type "Amex". Helm offers two identical options "Liabilities:CredCard:Amex". If I select the first option, the response is "There are no uncleared entries for Liabilities:CredCard:Amex". If I select the second option, then I'm given the unreconciled transaction and can proceed.

(I understand that I could stop using Helm with ledger mode, but I'm hoping that I won't have to do that.)

[sample-ledger.txt](https://github.com/ledger/ledger-mode/files/1911501/sample-ledger.txt)

**Comment by purcell** [comment] 2018-04-16 08:09
Thanks for the report. How recent is "recent"? Last couple of days?

**Comment by johnrakestraw** [comment] 2018-04-16 10:15
Sorry -- should have said more. Seems that the problem was introduced with commit 42c48b3 on 7 Dec 2017. It works with the previous commit (24b43e3 from 2 Sept 2017).

**Comment by doolio** [comment] 2024-01-04 13:45
@johnrakestraw is this still an issue for you? If not perhaps consider closing this issue. Thanks.

**Comment by bcc32** [comment] 2024-03-22 17:14
I couldn't reproduce this, and the completion code has changed a decent amount since the original report, so I suspect this is no longer an issue.  Please reopen or create a new issue with a valid sample ledger file if you still experience this with helm.

**Closed by bcc32** 2024-03-22 17:14 UTC
