### ISSUE TITLE
ledger-toggle-current stuck on EOF

### ISSUE THREAD

**Issue by markokocic** [ledger/ledger-mode#351] opened 2023-03-06 10:29 UTC
When trying to call `ledger-toggle-current` using `C-c C-c` if the transaction doesn't end with a new line, but with end of file, the call gets stuck, and I need to cancel it using `C-g`

This is when it gets stuck:
```
<cursor>2023-03-03 Something
    expense:aaa  1
    assets:something<EOF>
```
This one works:
```
<cursor>2023-03-03 Something
    expense:aaa  1
    assets:something
<EOF>
```
And this one also gets stuck:
```
<cursor>2023-03-03 Something
    expense:aaa  1
    assets:something
    <EOF>
```
Affected is the latest ELPA/MELPA version, but I remembre the same issue before.

**Comment by bcc32** [comment] 2024-03-18 20:33
Duplicate of #274

**Closed by bcc32** 2024-03-18 20:33 UTC
