### ISSUE TITLE
ledger-report-links-in-register doesn't work

### ISSUE THREAD

**Issue by johnrakestraw** [ledger/ledger-mode#109] opened 2018-04-15 00:17 UTC
With the current commit and the attached sample file, ledger-mode reports don't respect the "t" setting of ledger-report-links-in-register. I have the default (t) setting for this variable. With the attached file, running a simple reg report ("ledger reg blue") with ledger-mode yields the expected list of transactions, but the postings in the register aren't links back to the actual posting in the ledger file.

[sampleledger.txt](https://github.com/ledger/ledger-mode/files/1911489/sampleledger.txt)

**Comment by johnrakestraw** [comment] 2018-04-16 12:56
Additional info that I should have included before:

- Transactions in the report are linked (i.e., ledger-mode works as expected) with commit 7eaf1de3 on Jan 23. They don't appear as links with commit 80e50be0, also on January 23.
- The command I'm using to test this is "ledger reg assets:checking -d 'd>=[last month]' --sort date -X $ --no-revalued"

**Comment by johnrakestraw** [comment] 2018-04-16 23:35
@jabranham I wondered about that, too, based on the comment with the commit.
When I press e while in the report buffer, the command generating the report appears in the minibuffer with point so that I can edit the command.
If I put point on a line in the report and hit "return", the response in the minibuffer is "Buffer is read-only: #<buffer *Ledger Report*>"
(I'm on the edge of my knowledge with git here, so I should say why I think 80e50be is the problematic  commit. If I clone the repo and checkout 80e50be and then reload ledger-mode, then the report is generated without the links. If I then checkout 7eaf1de and reload ledger-mode, then the report is generated with the links.)

**Comment by jabranham** [comment] 2018-04-17 02:16
You didn't answer my question about whether or not you see `[[ledger-mode-flags]]` in the minnibuffer when you hit `e` in the report buffer. It's important that's there, as it's part of how ledger-mode calculates the buttons. 

ledger-mode calculates this automatically if you call reports via `C-c C-o C-r`.

**Comment by jabranham** [comment] 2019-10-10 16:18
@johnrakestraw When you hit `e` in the ledger-report buffer, you should see something like:

```
Report command line: ledger [[ledger-mode-flags]] -f /path/to/foo.ledger reg assets
```

If you don't see `[[ledger-mode-flags]]` then the links won't work.

**Comment by johnrakestraw** [comment] 2019-10-10 21:21
@jabranham  When i hit e in the ledger-report buffer, I see this in the minibuffer:

> ledger reg groceries -p oct

I don't see [[ledger-mode-flags]].

Bisect indicates that the commit below is the first one that doesn't work for me. Since others aren't reporting this problem, I assume this is something in my config. I ran the bisect tests with no .ledgerrc, and on my regular ledger file (~110K lines) and a very simple test file with only two entries. I'm (obviously) not a programmer -- can you suggest something I can do to find the problem?
=====
From git bisect:

e098be20cf603f48dfe18c6237546a8c49e1f97c is the first bad commit
commit e098be20cf603f48dfe18c6237546a8c49e1f97c
Author: Clément Pit-Claudel <cpitclaudel@gmail.com>
Date:   Fri Jan 26 21:08:32 2018 -0500

    Improve highlighting in reports (#73)

    * Select report width based on window-width

    Originally from GH-61, with adjustments.

    * Use buttons to indicate clickable lines in reports

    * Use ledger's native highlighting in reports

    * Document use-native-highlighting and report-clickable-face

    * Improve insertion of additional arguments into report commands

    Replace %(binary) with the path to ledger + any extra args instead of
    concatenating to the end of the report command.

    Suggested-By: @akater

    * Omit --columns, --color, etc. from command shown in report window

    Instead, use a special marker [[ledger-mode-args]], substituted in
    ledger-do-report.  As a bonus, this ensures that proper values are
    recomputed for --columns when pressing g in a report window

    * Document ledger-report-auto-width

 doc/ledger-mode.texi |   9 ++-
 ledger-fonts.el      |   4 +-
 ledger-report.el     | 159 ++++++++++++++++++++++++++++++++++-----------------
 3 files changed, 118 insertions(+), 54 deletions(-)
========
If I revert to the commit before this one, the links work, even though there's no [[ledger-mode-flags]] in the minibuffer when I hit e. (I wouldn't expect to see that, since apparently this was added in the commit above.)

If you can help me track this down, I'd really appreciate it. Please let me know if there's something I can provide that helps.

**Comment by jabranham** [comment] 2019-10-10 21:26
Can you reproduce this without loading your config?

You can also try bisecting your config to see if you can narrow down the
problem that way.

**Comment by johnrakestraw** [comment] 2019-10-10 23:49
Thanks for the prompt response.
I opened emacs with the following minimal .emacs:
---
(defun set-exec-path-from-shell-PATH ()
"Sets the exec-path to the same value used by the user shell"
(let ((path-from-shell
	(replace-regexp-in-string
	 "[[:space:]\n]*$" ""
	 (shell-command-to-string "$SHELL -l -c 'echo $PATH'"))))
  (setenv "PATH" path-from-shell)
  (setq exec-path (split-string path-from-shell path-separator))))

  ;; call function now
  (set-exec-path-from-shell-PATH)  (setq inhibit-startup-message t)
(defvar emacs-site-lisp-directory (concat (getenv "EMACS_DIR") "/site-lisp/"))

(add-to-list 'load-path "~/ledger-mode/")
(require 'ledger-mode)
---
I have no .ledgerrc file. I get the same results as before when I run a reg report -- no [[ledger-mode-flags]] in the minibuffer when I press "e" and the postings in a reg report aren't linked to the entries in my ledger file.

**Comment by jabranham** [comment] 2019-10-10 23:53
Well, I'm at a loss on this one. How are you installing ledger mode? Is it
possible you are loading outdated byte code?

**Comment by johnrakestraw** [comment] 2019-10-11 00:00
Thanks again. I'm cloning ledger-mode from this github repo. I'm not sure how I might be loading outdating byte code -- as you can see, I'm loading the path to the ledger-mode directory in my .emacs, and that's the directory I used in the git bisect work I did earlier this afternoon.
Obviously I don't know nearly as much about this as you do, but it's certainly a mystery to me. Something about the change in commit e098be2 doesn't play well with my set-up.

**Comment by jabranham** [comment] 2019-10-11 13:08
So if you do:

```
cd ~/ledger-mode
git checkout master
git pull
make -C test compile
emacs -Q
(and then in Emacs do:)
(add-to-list 'load-path "~/ledger-mode")
(require 'ledger-mode)
C-x C-f /path/to/your/ledger-file
C-c C-o C-r RET
account RET
(choose your account)
```

And then in the report buffer, put point on a date and press `RET`. You're saying that it doesn't put you back in the ledger file?

**Comment by johnrakestraw** [comment] 2019-10-11 16:22
Thanks again for your patience and follow-up. I walked through these instructions:

- git checkout master and git pull generated response that I was already on master and up to date
- make -C test compile generated no errors 
- in Emacs, I executed eval-last-sexp on each of the parenthetical commands. 
- after loading my ledger, when requesting the report, I added -f option specifying my ledger-file
- in the report buffer, i put point on a date and pressed RET. Response in minibuffer is "Buffer is read-only: #<buffer *Ledger Report*>"
- pressing "e" while in report buffer gives me that report command (with options) in minibuffer, but no [[ledger-mode-flags]].

Two further comments -- I tried this both with my regular ledger file and with a test file including only two postings. And I tried this both on my mac and on an ubuntu server I'm running headless. No joy with either file on either computer.

Mystifying.

**Comment by johnrakestraw** [comment] 2019-10-11 16:29
apologies. operator error here. (This is embarrassing.)

I was running my own report command instead of the simple "account."

If I run the account report, choosing my account. then it works. 
So there's a problem with how I'm generating the report. I'm going to do some more testing, but sending this message now so you won't waste any more time before I learn something.

**Comment by johnrakestraw** [comment] 2019-10-11 20:17
The problem was that I was using setq to define the ledger-reports variable in the my config file rather than by using the customize feature. I don't know whether this is a correct use of setq, but the reports worked just fine (including the links) before the commit mentioned above.

Now that I've rebuilt the ledger-reports variable using customize, the reports are working again.

One problem -- if I build the report command in the minibuffer (rather than use the report templates in the variable ledger-reports -- e.g., ledger reg account -p oct), then I have the same behavior as before -- the lines in the report window are not links to the ledger file. 

Apologies for the noise -- and thanks again for the explicit coaching that led me to discover the problem.

**Comment by jabranham** [comment] 2019-10-12 13:42
> The problem was that I was using setq to define the ledger-reports variable in the my config file

that shouldn't be an issue (it's what I do and it works for me). Glad to hear it's working for you now though.

> One problem -- if I build the report command in the minibuffer (rather than use the report templates in the variable ledger-reports -- e.g., ledger reg account -p oct), then I have the same behavior as before -- the lines in the report window are not links to the ledger file.

Right - you'll have to add `[[ledger-mode-flags]]` in the minibuffer.

Sounds like all is well now; closing this issue.

**Closed by jabranham** 2019-10-12 13:42 UTC
